#ifndef _CONFIG_SYMBOLS_
#define _CONFIG_SYMBOLS_

#define SERVER_USERNAME  CONFIG_SERVER_USERNAME
#define SERVER_PASSWORD  CONFIG_SERVER_PASSWORD
#define GPIO_HALL_SENSOR CONFIG_GPIO_HALL_SENSOR
#define GPIO_TEMPERATURE CONFIG_GPIO_TEMPERATURE
#define GPIO_HUMIDITY    CONFIG_GPIO_HUMIDITY

#endif